Lesson 3
ShishkinAndrey/PY200_Spring_2021 pull request #1
Opened 2021-02-10 07:02 UTC by ShishkinAndrey

Шишкин Андрей Сергеевич

2021-02-10 09:36 UTC, aeksei requested changes
---

Если стоит статус **Changes requested**, то нужно в данную ветку внести обязательные изменения, которые представлены ниже. Если выше представлены комментарии, то они носят рекомендательный характер.
После нужно сделать "push", тогда коммиты с изменениями сразу попадут в "pull request". 
После этого нужно будет запросить "re-request review"

2021-02-10 09:36 UTC, aeksei commented on lesson_3/linked_list.py
>      def __getitem__(self, item: int) -> Any:
Добавить к аннотации типов slice

2021-02-10 09:36 UTC, aeksei commented on lesson_3/linked_list.py
> +                return current_node.value
Код для возврата что положительного, что отрицательного индекса одинаков. Тогда может логичнее сделать 
```python
item = item if item >= 0 else self.__len + item
for _ in range(item):
    current_node = current_node.next
return current_node.value
```
Дубляж кода не всегда хорошо

2021-02-10 09:36 UTC, aeksei commented on lesson_3/linked_list.py
> +            current_node = current_node.next
Вижу по коду много перемещений по узлам, лучше вынести эту логику в отдельный встроенный метод, и пользоваться им. Вдруг по каким-то причинам, логика перемещения по узлам изменится. Это надо будет по всем коду менять. А так есть метод, и пользуемся им

2021-02-10 09:36 UTC, aeksei commented on lesson_3/linked_list.py
> +            raise IndexError()
Почему по отрицательному индексу можно получить элемент, а поставить нельзя?
Вынесите это опять же в отдельный метод, и используйте в __getitem__ и __setitem__, тогда и там и там будет одинаковое поведение, и опять же нет дубляжа кода, меньше вероятности допустить ошибку

2021-02-10 09:36 UTC, aeksei commented on lesson_3/linked_list.py
> +            yield elem
Вопрос прям очень с подковыркой))) Решение очень элегантное))
И мне бы интересно было понять, сможете ли вы оценить его с точки зрения O-нотации.
Какая сложность этой операции в текущей версии LinkedList

Подумайте, с ответом я не тороплю. На практике можем пообсуждать этот момент

2021-02-10 09:36 UTC, aeksei commented on lesson_3/linked_list.py
> +                current_node = current_node.next
Опять же вопрос на затравку и наверное уровня собеседования))

Считаете ли вы вашу реализацию эффективной? Или зная, что LinkedList имея работать с циклом for, за счет __getitem__ сделая вот так элегантно, ничего не изменится?
```python
for i, node_value in enumerate(self):
    if node_value == value:
        return i
```

raise ValueError(f'{value} not in list')

2021-02-10 09:36 UTC, aeksei commented on lesson_3/linked_list.py
> +        raise ValueError(f'{value} not in list')
не list лучше,  а `self.__class__.__name__`

2021-02-10 09:36 UTC, aeksei commented on lesson_3/linked_list.py
> +            correct_compare = False
Опять же косметическая поправка, если цикл должен хотя бы один раз выполниться, можно использовать цикл с постусловием

2021-02-10 09:36 UTC, aeksei commented on lesson_3/linked_list.py
> +                current_elem = current_elem.next
Давайте вспомним, что за сортировка, и какая сложность?

2021-02-11 11:53 UTC, ShishkinAndrey commented on lesson_3/linked_list.py
> +            yield elem
Спасибо за интересный вопрос) я понимаю, что создается копия списка, в который начиная с последнего элемента с шагом -1 добавляются по элементу.
Поэтому мой ответ О(n)

2021-02-11 12:00 UTC, ShishkinAndrey commented on lesson_3/linked_list.py
> +                current_node = current_node.next
Если я правильно понял, то сложность моей реализации O(n), а сложность вашей предложенной реализации О(n*n)

2021-02-11 12:03 UTC, ShishkinAndrey commented on lesson_3/linked_list.py
> +            correct_compare = False
Алексей, прошу пояснить данный комментарий. Ведь если список отсортирован, то сложность составит О(n) в лучшем случае. Какое постусловие лучше использовать?

2021-02-11 12:05 UTC, ShishkinAndrey commented on lesson_3/linked_list.py
> +                current_elem = current_elem.next
Пузырьковая сортировка. Сложность О(n^2). Лучше другую реализовать?

2021-02-17 16:39 UTC, aeksei commented on lesson_3/linked_list.py
> +                current_elem = current_elem.next
Не, этой абсолютно достаточно))

2021-02-17 16:45 UTC, aeksei commented on lesson_3/linked_list.py
> +            yield elem
Но получение каждого элемента идет с головы из-за особенностей getitem. Поэтому всё что завязано на getitem, а именно на её внутреннюю реализацию, занимает O(n^2)

2021-02-17 17:51 UTC, aeksei commented on lesson_3/linked_list.py
> +            correct_compare = False
while True:
    ...
    # сортировка
    if not correct_compare:
        break

2021-02-17 17:53 UTC, aeksei approved these changes
Проверено. У меня по этому заданию вопросов больше нет

Отлично, только по-моему вы потеряли возможность работы с отрицательными индексам. Проверка для них есть, но логики работы с ними я не увидел.

---

Если стоит **Changes approved**, то смело можно сливать ветки. 
И после слияния удалять ветку.

Всё что указано просто комментариями, носит рекомендательный характер.
Для моментов, которые нужно исправить, я буду запрашивать изменения.

2021-02-24 19:09 UTC, merged